### ISSUE TITLE
CUDA out of memory for large systems

### ISSUE THREAD

**Issue by amin-sagar** [otayfuroglu/deepQM#3]
Dear deepQM developers,
I have been recently trying to run deepQM on a protein-ligand complex where the protein is around 700 residues long.
This gives me the following error on both CPU and GPU
```
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Warning: an error was encountered.
CUDA out of memory in case of aimnet model or your system may contain elements such as "F, Cl and S".
```
I am using
```
model_list="ani2x dftd3"
```
I have RXT 3090 with 24 GB of memory and when using CPUs only, I have 512 GB of system memory.
During the calculation, I don't see the memory usage go very high, although it's possible that I miss a very short lived peak in memory usage.
I have two questions.
1) Have you experienced such issues with similar system sizes?
2) If I truncate the system by only keeping the residues within 10 A of the ligand, as done for comparison with Gaussian in the deepQM paper, I can run the calculations. Is this an acceptable way of calculating affinities in a practical case or is it only meant for comparison with Gaussian as it can't deal with such large systems and shouldn't be used as a general way to calculate affinities?

I would be really grateful for your suggestions.

Best,
Amin.

**Comment by amin-sagar** [comment]
Hello.
It's great to know that your are getting good results for protein-protein complexes #2 
I am working on protein-peptide complexes and keep running into out of memory errors.
Have you encountered this while working on protein-protein complexes?
If yes, did you find a work around?

I would be really grateful for any suggestions.
Best,
Amin.

**Comment by modellab-gtu** [comment]
Hi Amin,

We have actually encountered a similar problem of out of memory especially when dftd3 is specified as the calculator in the case of thousands of solvent molecules included. However, for the protein-ligand complexes, we did not have any issue. As for the protein-peptides, we are currently running, we still do not get any errors with the use of ani-2x as the only calculator (at least yet!).  We have not tried ani-2x+dftd3 yet. 

Apart from this, in the paper, we have shown the truncated protein-ligand structures in order to do QM calculations. Otherwise, we only reduce the system size when dealing with solvents (only considering the solvents 10A around the complex) not protein-ligand or protein-peptide. 

I would suggest to you to carry out the following as an inspection before considering truncating the system:

1) When running on GPU/CPU, please try to reduce the parallel jobs (cpu_use) as low as 1.
2) Try ani2x only as the calculator (using 1 cpu/gpu). If it works try dftd3 only as the calculator (using 1 cpu/gpu). I believe the dft-d3 would fail rather than ani-2x.
3) Try loading less number of frames in the calculation (You can split the trajectory into a few pieces) and then finally combine the results.

If none of these work, you could think truncating the system.

If dft-d3 is the problem, as shown in our paper, its improvement to ani-2x is as little as 1-2%. So you could totally ignore this term in the calculations.

Hope this helps

Bests

**Comment by modellab-gtu** [comment]
As for the truncation of the system, it should still give similar results as long as you are consistent in the residues that are around the peptide throughout the simulation. ANI itself has cutoff values for the environment in the training and thus is limited to cover only short range interactions. Although it could be a little bit tricky to define all residues that are involved in the interaction from one snapshot to another in order to have the same atoms in the system for each frame, truncation should still be doable.

**Comment by amin-sagar** [comment]
Thanks @modellab-gtu 

I tried your suggestions.

You are right, the out of memory error are from dftd3. When I use just ani2x as the calculator, everything works nicely.
With dtfd3, I get out of memory error even if I use CPU and just 1 parallel job. This is strange as I never see memory usage peaking.

My experiments with protein-peptide complexes suggest that the value of alpha needs to be increased and beta decreased to fit the experimental affinity values. That's why I was trying to use dftd3. Have you seen a similar behavior?
Would it be possible for you to share the coefficients you are using for protein-protein and protein-peptide complexes?

Thanks a lot for your help.

**Comment by modellab-gtu** [comment]
These coefficients were produced for protein-ligand interactions and in particular main protease-inhibitor interactions. Therefore, for protein-peptide complexes, it would more likely to have different values. We will probably pubislh new coefficients when we complete our peptide library. But for now, in terms of relative energies (disregarding the absolute values), it should give catch the trend. Unfortunately, due to busy schedule of my student , our progress in this is very slow.

**Comment by amin-sagar** [comment]
Thanks @modellab-gtu 

I look forward to the publications.

One more question - Why should all the snapshots have the same atoms? Are we not concerned only about the difference of the energies between P+L and PL? Is it because the scaling factor changes with the number/identity of atoms?

**Comment by modellab-gtu** [comment]
it will be using average energies in the end. We want the errors accumulated on one snapshot to cancel out the error in the other snapshot. You could try but differences may not be comparable any more from one snapshot to another.

**Comment by amin-sagar** [comment]
Thanks.
